/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processor.genericeditor.windows.conditions;

import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.jgrapht.graph.DefaultDirectedGraph;
import processor.core.file.ProjectCentral;
import processor.core.graph.DecisionEdge;
import processor.core.graph.GraphNode;
import processor.profile.DIEmulator;

/**
 *
 * @author cbaez
 */
public class InPanel extends javax.swing.JPanel {
    DefaultDirectedGraph graph =  DIEmulator.getProfile().getGraph();
    GraphNode node;

    /**
     * Creates new form InPanel
     */
    public InPanel(GraphNode node) {
        this.node = node;
        initComponents();
        loadPorts();
        
    }

    public void loadPorts() {
        Set<DecisionEdge> incomingEdgesOf = graph.incomingEdgesOf(node);
        List<GraphNode> pointingGraphs = new LinkedList<>();
        incomingEdgesOf.forEach(e -> {
            pointingGraphs.add((GraphNode) graph.getEdgeSource(e));
        });
        jTextField1.setText(pointingGraphs.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jLabel1.setText("In:"); // NOI18N
        add(jLabel1);

        jTextField1.setEditable(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(60, 20));
        add(jTextField1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
