/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.datapro.nfp.ui.windows.conditions;

import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import com.datapro.nfp.core.file.ProjectCentral;
import com.datapro.nfp.core.graph.DecisionGraph;
import com.datapro.nfp.core.graph.GraphNode;
import com.datapro.nfp.profile.DIEmulator;

/**
 *
 * @author cbaez
 */
public class OutPanel extends javax.swing.JPanel {

    DecisionGraph graph = DIEmulator.getProfile().getGraph();
    GraphNode node;

    /**
     * Creates new form OutPanel
     */
    public OutPanel(GraphNode node) {
        this.node = node;
        initComponents();
        loadPorts();
    }

    public void loadPorts() {
        GraphNode trueTarget = graph.getDecisionTargetOf(node, true);
        GraphNode falseTarget = graph.getDecisionTargetOf(node, false);
        
        Set vertexSet = graph.vertexSet();
        
        DefaultComboBoxModel model1 = new DefaultComboBoxModel();
        DefaultComboBoxModel model2 = new DefaultComboBoxModel();
        vertexSet.forEach(v -> {
            if(v.equals(node) || v.equals(DecisionGraph.START_NODE))
                return;
            model1.addElement(v);
            model2.addElement(v);
        });
        jComboBox1.setModel(model1);
        jComboBox2.setModel(model2);
        
        
        
        jComboBox1.setSelectedItem(trueTarget);
        jComboBox2.setSelectedItem(falseTarget);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jLabel1.setText("True:");
        add(jLabel1);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);

        jLabel2.setText("False");
        add(jLabel2);

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
      
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
         
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        graph.changeEdgeOf(node, true, (GraphNode) jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        graph.changeEdgeOf(node, false, (GraphNode) jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
